#!/usr/bin/env python3
"""Generate public/sitemap.xml from _catalogue/catalogue.json.

The app uses hash routing, so URLs look like
    https://sarangvehale.github.io/neiro/#/library/album/<id>
Modern crawlers (Google since 2015) follow hash fragments and execute the
client-side JS, so listing them gives proper coverage. For perfect SEO a
future build step should also render per-album HTML pages and link those
instead — flagged in a comment in the output XML.

Run after build_catalogue.py — wired into the GitHub Actions deploy step.
"""
from __future__ import annotations
import json
import os
import sys
from pathlib import Path
from datetime import date

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://sarangvehale.github.io/neiro"
CATALOGUE = ROOT / "_catalogue" / "catalogue.json"
OUT = ROOT / "public" / "sitemap.xml"


def emit_url(loc: str, *, changefreq: str = "monthly", priority: float = 0.5) -> str:
    return (
        "  <url>\n"
        f"    <loc>{loc}</loc>\n"
        f"    <changefreq>{changefreq}</changefreq>\n"
        f"    <priority>{priority}</priority>\n"
        "  </url>\n"
    )


def main() -> int:
    if not CATALOGUE.exists():
        print(f"[build_sitemap] {CATALOGUE} missing — run build_catalogue.py first", file=sys.stderr)
        return 1

    cat = json.loads(CATALOGUE.read_text())
    artists = cat.get("artists", [])

    parts: list[str] = [
        '<?xml version="1.0" encoding="UTF-8"?>\n',
        "<!-- Generated by scripts/build_sitemap.py; do not hand-edit.\n",
        "     Per-album URLs use hash fragments because NEIRO is a SPA. For\n",
        "     stronger SEO a future build step should render static per-album\n",
        f"     HTML pages and link those instead. Generated {date.today().isoformat()}. -->\n",
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n',
        # Canonical entry — highest priority
        emit_url(f"{SITE}/", changefreq="weekly", priority=1.0),
        # Top-level routes
        emit_url(f"{SITE}/#/library", changefreq="weekly", priority=0.9),
        emit_url(f"{SITE}/#/artists", changefreq="weekly", priority=0.8),
        emit_url(f"{SITE}/#/contribute", changefreq="monthly", priority=0.6),
        emit_url(f"{SITE}/#/about",      changefreq="yearly",  priority=0.4),
    ]

    n_artists = 0
    n_albums = 0
    for a in artists:
        if not a.get("id"):
            continue
        parts.append(emit_url(f"{SITE}/#/artists/artist/{a['id']}", changefreq="monthly", priority=0.6))
        n_artists += 1
        for al in a.get("albums", []):
            if not al.get("id"):
                continue
            parts.append(emit_url(f"{SITE}/#/library/album/{al['id']}", changefreq="monthly", priority=0.7))
            n_albums += 1

    parts.append("</urlset>\n")
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"[build_sitemap] wrote {OUT} — {n_artists} artists + {n_albums} albums + 5 routes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
